-- TRIGGER PARA LOG DA TABELA UPDATE_SAMPLE --
DROP TRIGGER TR_ACOMPANHAMENTO_SAMPLE;
CREATE TRIGGER TR_ACOMPANHAMENTO_SAMPLE
AFTER UPDATE ON SAMPLE
FOR EACH ROW
BEGIN
    INSERT INTO UPDATE_SAMPLE (ID_CHASSI, ID_BOLETIM, MENSAGEM, ID_USUARIO_ALTERANTE, DT_EDICAO)
    VALUES (:OLD.ID_CHASSI, :OLD.ID_BOLETIM, CONCAT(CONCAT((SELECT bol.ITEM FROM BOLETIM bol WHERE bol.ID_BOLETIM = :OLD.ID_BOLETIM) ,' available to chassi '), (SELECT cha.CHASSI FROM CHASSI cha WHERE cha.ID_CHASSI = :OLD.ID_CHASSI)), 1, CURRENT_TIMESTAMP);
END;

-- TESTE DA TRIGGER --
UPDATE
  SAMPLE
SET
  STATUS_SAMPLE = 'INCORPORATED'
WHERE
  ID_SAMPLE = 2



-- TESTE DA TRIGGER --
UPDATE SAMPLE SET STATUS_SAMPLE = 'INCORPORATED' WHERE ID_SAMPLE = 1;
UPDATE SAMPLE SET STATUS_SAMPLE = 'INCORPORATED' WHERE ID_SAMPLE = 2;
UPDATE SAMPLE SET STATUS_SAMPLE = 'INCORPORATED' WHERE ID_SAMPLE = 9;
UPDATE SAMPLE SET STATUS_SAMPLE = 'INCORPORATED' WHERE ID_SAMPLE = 10;
UPDATE SAMPLE SET STATUS_SAMPLE = 'INCORPORATED' WHERE ID_SAMPLE = 17;
UPDATE SAMPLE SET STATUS_SAMPLE = 'INCORPORATED' WHERE ID_SAMPLE = 18;
UPDATE SAMPLE SET STATUS_SAMPLE = 'INCORPORATED' WHERE ID_SAMPLE = 25;
UPDATE SAMPLE SET STATUS_SAMPLE = 'INCORPORATED' WHERE ID_SAMPLE = 26;
UPDATE SAMPLE SET STATUS_SAMPLE = 'INCORPORATED' WHERE ID_SAMPLE = 27;
UPDATE SAMPLE SET STATUS_SAMPLE = 'INCORPORATED' WHERE ID_SAMPLE = 31;
UPDATE SAMPLE SET STATUS_SAMPLE = 'INCORPORATED' WHERE ID_SAMPLE = 32;
UPDATE SAMPLE SET STATUS_SAMPLE = 'INCORPORATED' WHERE ID_SAMPLE = 37;
UPDATE SAMPLE SET STATUS_SAMPLE = 'INCORPORATED' WHERE ID_SAMPLE = 38;
UPDATE SAMPLE SET STATUS_SAMPLE = 'INCORPORATED' WHERE ID_SAMPLE = 44;
UPDATE SAMPLE SET STATUS_SAMPLE = 'INCORPORATED' WHERE ID_SAMPLE = 45;

  
  
DELETE FROM UPDATE_SAMPLE
  SELECT * FROM UPDATE_SAMPLE