-- TRIGGER PARA LOG DA TABELA UPDATE_SAMPLE --
DROP TRIGGER TR_ACOMPANHAMENTO_SAMPLE;
CREATE TRIGGER TR_ACOMPANHAMENTO_SAMPLE
AFTER UPDATE ON SAMPLE
FOR EACH ROW
BEGIN
    INSERT INTO UPDATE_SAMPLE (ID_CHASSI, ID_BOLETIM, MENSAGEM, ID_USUARIO_ALTERANTE, DT_EDICAO)
    VALUES (:OLD.ID_CHASSI, :OLD.ID_BOLETIM, CONCAT(CONCAT((SELECT bol.ITEM FROM BOLETIM bol WHERE bol.ID_BOLETIM = :OLD.ID_BOLETIM) ,' available to chassi '), (SELECT cha.CHASSI FROM CHASSI cha WHERE cha.ID_CHASSI = :OLD.ID_CHASSI)), 1, CURRENT_TIMESTAMP);
END;

-- TESTE DA TRIGGER --
UPDATE
  SAMPLE
SET
  STATUS_SAMPLE = 'INCORPORATED'
WHERE
  ID_SAMPLE = 2

DELETE FROM UPDATE_SAMPLE
SELECT * FROM UPDATE_SAMPLE